# MySQL.  Versions 4.1 and 5.0 are recommended.
#
#
# Be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: mangocms_development
  pool: 5
  username: root   
  password: tonglijia.
  host: localhost

# test:
#   adapter: mysql2
#   encoding: utf8
#   reconnect: false
#   database: mangocms_test_test
#   pool: 5
#   username: rordevel
#   password: 
#   host: 192.168.0.243

# production:
#   adapter: jdbcmysql
#   encoding: utf8
#   reconnect: false
#   database: mangocms_test_production
#   pool: 5
#   username: rordevel
#   password: 
#   host: 192.168.0.243

#
